{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyN+LkBEQ4Jjw8GDwfkICXRE"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["Q1. What is an Exeption in python? Write the difference between Exceptions and syntax errors?"],"metadata":{"id":"rNz7DE_RFPkl"}},{"cell_type":"markdown","source":["=>An exception in Python is an error that occurs during the execution of a program. It may be due to various reasons such as invalid input, division by zero, out of memory, or trying to access an undefined variable. When an exception occurs, the normal flow of the program is disrupted, and the program terminates.\n","\n","The key difference between exceptions and syntax errors is that exceptions occur during the execution of a program, while syntax errors occur before the program is executed. Additionally, exceptions can be handled and resolved programmatically, while syntax errors must be fixed manually by the programmer\n"],"metadata":{"id":"ZY_6z_iaFTKW"}},{"cell_type":"markdown","source":["Q2. What happens when an exception is not handled? Explain with an example"],"metadata":{"id":"WPsAwD_KZ-lr"}},{"cell_type":"markdown","source":["=>When an exception is not handled, the program terminates abruptly and generates a traceback, which is a detailed report of the error that occurred. The traceback provides information about the line of code where the error occurred, the type of error, and a description of the error.\n"],"metadata":{"id":"mynS_WSnaG-l"}},{"cell_type":"code","execution_count":1,"metadata":{"id":"VbZmwQAfFFyB","executionInfo":{"status":"ok","timestamp":1688197450392,"user_tz":-330,"elapsed":4,"user":{"displayName":"Kalpesh Patil","userId":"17000745813800247736"}}},"outputs":[],"source":["def cls(x,y):\n","    result= x/y\n","    return result"]},{"cell_type":"code","source":["l= cls(5,0)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":259},"id":"Ci9Zaes7aJ-B","executionInfo":{"status":"error","timestamp":1688197457732,"user_tz":-330,"elapsed":10,"user":{"displayName":"Kalpesh Patil","userId":"17000745813800247736"}},"outputId":"120c95d4-4d57-48c7-b7cc-4d2d1b8e157a"},"execution_count":2,"outputs":[{"output_type":"error","ename":"ZeroDivisionError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-2-6b6d003bd7a8>\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0ml\u001b[0m\u001b[0;34m=\u001b[0m \u001b[0mcls\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m5\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m<ipython-input-1-28b43fd636a8>\u001b[0m in \u001b[0;36mcls\u001b[0;34m(x, y)\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mdef\u001b[0m \u001b[0mcls\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mx\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0my\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m     \u001b[0mresult\u001b[0m\u001b[0;34m=\u001b[0m \u001b[0mx\u001b[0m\u001b[0;34m/\u001b[0m\u001b[0my\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      3\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0mresult\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"]}]},{"cell_type":"markdown","source":["Q3. Which Python statements are used to catch and handle exceptions? Explain with an example"],"metadata":{"id":"I1pgVoRMaRcU"}},{"cell_type":"markdown","source":["=>In Python, exceptions can be caught and handled using the try and except statements. The try block contains the code that might raise an exception, and the except block contains the code that will handle the exception if it occurs.\n","\n","Here is an example of how to use the try and except statements to handle a ZeroDivisionError exception:"],"metadata":{"id":"w959azPbaZh7"}},{"cell_type":"code","source":["def cls(x,y):\n","  try:\n","    result= x/y\n","  except ZeroDivisionError :\n","    print(\"can not divide by zero\")\n","\n","  else:\n","    return result"],"metadata":{"id":"LA4_RvOjaOJ3","executionInfo":{"status":"ok","timestamp":1688197513149,"user_tz":-330,"elapsed":9,"user":{"displayName":"Kalpesh Patil","userId":"17000745813800247736"}}},"execution_count":3,"outputs":[]},{"cell_type":"code","source":["l= cls(5,0)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"fPgFLX8Zabxg","executionInfo":{"status":"ok","timestamp":1688197521023,"user_tz":-330,"elapsed":9,"user":{"displayName":"Kalpesh Patil","userId":"17000745813800247736"}},"outputId":"9b5dffd2-6a26-4b86-bdbe-4c89aec398fb"},"execution_count":4,"outputs":[{"output_type":"stream","name":"stdout","text":["can not divide by zero\n"]}]},{"cell_type":"markdown","source":["Q4. Explain with an example:#\n","\n","=>try and else\n","\n","=>finally\n","\n","=>raise"],"metadata":{"id":"efv8cZAWalts"}},{"cell_type":"code","source":["#try and else\n","def multiplay(x,y):\n","  try:\n","    result= x*y\n","  except Exception as e:\n","    print(\"this is exception block\", e)\n","  else:\n","    return  result"],"metadata":{"id":"Nt_1nQ67adrw","executionInfo":{"status":"ok","timestamp":1688197571395,"user_tz":-330,"elapsed":5,"user":{"displayName":"Kalpesh Patil","userId":"17000745813800247736"}}},"execution_count":5,"outputs":[]},{"cell_type":"code","source":["print(multiplay(10,15))"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"z4Qv1MwJap7e","executionInfo":{"status":"ok","timestamp":1688197578914,"user_tz":-330,"elapsed":7,"user":{"displayName":"Kalpesh Patil","userId":"17000745813800247736"}},"outputId":"dbc76074-d02a-4bff-9fbe-02951f242628"},"execution_count":6,"outputs":[{"output_type":"stream","name":"stdout","text":["150\n"]}]},{"cell_type":"code","source":["#finally\n","def add(x,y):\n","  try:\n","    result= x+y\n","  finally :\n","    return result\n"],"metadata":{"id":"6zXlGJkWarun","executionInfo":{"status":"ok","timestamp":1688197585659,"user_tz":-330,"elapsed":7,"user":{"displayName":"Kalpesh Patil","userId":"17000745813800247736"}}},"execution_count":7,"outputs":[]},{"cell_type":"code","source":["print(add(7,8))"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"W8O1qzMPatS2","executionInfo":{"status":"ok","timestamp":1688197594573,"user_tz":-330,"elapsed":5,"user":{"displayName":"Kalpesh Patil","userId":"17000745813800247736"}},"outputId":"d4ed7132-ab3d-4dbd-9283-e20ddc786e79"},"execution_count":8,"outputs":[{"output_type":"stream","name":"stdout","text":["15\n"]}]},{"cell_type":"code","source":["#raise\n","def divied(x,y):\n","  if y == 0:\n","      raise ZeroDivisionError(\"can not divied by zero\")\n","  return x/y\n","try :\n","    print(divied(10,2))\n","    print(divied(10,0))\n","\n","except ZeroDivisionError as e:\n","    print(e)\n","\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"UzPUE7P_avhX","executionInfo":{"status":"ok","timestamp":1688197602094,"user_tz":-330,"elapsed":5,"user":{"displayName":"Kalpesh Patil","userId":"17000745813800247736"}},"outputId":"abb49b1e-bbce-4042-aa1f-a41edb3463ea"},"execution_count":9,"outputs":[{"output_type":"stream","name":"stdout","text":["5.0\n","can not divied by zero\n"]}]},{"cell_type":"markdown","source":["Q5. What are Custom Exceptions in python? What do we need Custom Exceptions ? Explain in with an example\n","\n","=>Custom exceptions are user-defined exceptions in Python. They allow you to define specific types of exceptions for your application, so you can handle errors and exceptions in a more organized and meaningful way.\n","\n","For example, consider a scenario where you are writing a library that performs some mathematical calculations. In this library, you may encounter several different types of errors, such as invalid input, overflow, and divide-by-zero errors. You could handle these errors by raising built-in exceptions, such as ValueError or ZeroDivisionError, but it may not provide enough context or information about the error that has occurred."],"metadata":{"id":"3zWQX7Fsa1lI"}},{"cell_type":"code","source":["balance= int(input(\"enter your balance \"))"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"UBMKR344axSX","executionInfo":{"status":"ok","timestamp":1688197703588,"user_tz":-330,"elapsed":5163,"user":{"displayName":"Kalpesh Patil","userId":"17000745813800247736"}},"outputId":"bc0eea2d-3b76-4cd3-89df-31d4611a70f8"},"execution_count":14,"outputs":[{"name":"stdout","output_type":"stream","text":["enter your balance 5000\n"]}]},{"cell_type":"code","source":["class validbalance(Exception):\n","\n","  def __init__(self,mag):\n","    self.mag= mag\n"],"metadata":{"id":"FfzS6Zxha6GI","executionInfo":{"status":"ok","timestamp":1688197703590,"user_tz":-330,"elapsed":21,"user":{"displayName":"Kalpesh Patil","userId":"17000745813800247736"}}},"execution_count":15,"outputs":[]},{"cell_type":"code","source":["def validatbalance(balance):\n","  if balance < 0:\n","    raise validbalance(\"balance is nagetive\")\n","  elif balance >= 10000:\n","    raise validbalance(\"enter balance is very high \")\n","  else:\n","    print(\"enter balance is valied\")\n"],"metadata":{"id":"1UYA0GQWa8Xx","executionInfo":{"status":"ok","timestamp":1688197703592,"user_tz":-330,"elapsed":12,"user":{"displayName":"Kalpesh Patil","userId":"17000745813800247736"}}},"execution_count":16,"outputs":[]},{"cell_type":"code","source":["try :\n","  balance= int(input(\"enter your balance \"))\n","  validatbalance(balance)\n","except validbalance as e :\n","  print(e)\n","\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"WiuPN_-Va92v","executionInfo":{"status":"ok","timestamp":1688197707899,"user_tz":-330,"elapsed":4318,"user":{"displayName":"Kalpesh Patil","userId":"17000745813800247736"}},"outputId":"dffb6dd5-d4e6-4f66-fb99-70e2dae09888"},"execution_count":17,"outputs":[{"output_type":"stream","name":"stdout","text":["enter your balance 11000\n","enter balance is very high \n"]}]},{"cell_type":"markdown","source":["Q6. Create a custom exception class. Use this class to handle an exception."],"metadata":{"id":"IFl3-PxubVDf"}},{"cell_type":"code","source":["class CustomException(Exception):\n","   pass\n","\n","def divide(x,y):\n","    if y == 0:\n","       raise CustomException(\"can not divide by zero\")\n","    return x / y\n","\n","try:\n","  print(divide(66,3))\n","  print(divide(15,0))\n","except CustomException as e:\n","  print(e)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"BVfpXBBma_qm","executionInfo":{"status":"ok","timestamp":1688197766951,"user_tz":-330,"elapsed":6,"user":{"displayName":"Kalpesh Patil","userId":"17000745813800247736"}},"outputId":"ef231aef-b490-4878-cbf5-b474ed438291"},"execution_count":18,"outputs":[{"output_type":"stream","name":"stdout","text":["22.0\n","can not divide by zero\n"]}]},{"cell_type":"code","source":[],"metadata":{"id":"Dlo5R0iAbZpn"},"execution_count":null,"outputs":[]}]}