{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyOYoJypsEY5uUchQ+MIhjM/"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["Q3. Which Python statements are used to catch and handle exceptions? Explain with an example"],"metadata":{"id":"99-rFSEQJlDl"}},{"cell_type":"markdown","source":["=>In Python, exceptions can be caught and handled using the try and except statements. The try block contains the code that might raise an exception, and the except block contains the code that will handle the exception if it occurs.\n","\n","Here is an example of how to use the try and except statements to handle a ZeroDivisionError exception:\n"],"metadata":{"id":"qQM-RLJxJ4QK"}},{"cell_type":"code","execution_count":11,"metadata":{"id":"jUNkZsfUJg7h","executionInfo":{"status":"ok","timestamp":1687455357608,"user_tz":-330,"elapsed":9,"user":{"displayName":"Kalpesh Patil","userId":"17000745813800247736"}}},"outputs":[],"source":["def cls(x,y):\n","  try:\n","    result= x/y\n","  except ZeroDivisionError :\n","    print(\"can not divide by zero\")\n","\n","  else:\n","    return result"]},{"cell_type":"code","source":["l= cls(5,0)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"bAktt_VLKZ-l","executionInfo":{"status":"ok","timestamp":1687455358469,"user_tz":-330,"elapsed":7,"user":{"displayName":"Kalpesh Patil","userId":"17000745813800247736"}},"outputId":"f2fd7d81-0fef-44cf-a343-6e3cbd796484"},"execution_count":12,"outputs":[{"output_type":"stream","name":"stdout","text":["can not divide by zero\n"]}]},{"cell_type":"code","source":[],"metadata":{"id":"ZOnzaqcwKnUT"},"execution_count":null,"outputs":[]}]}